import Foundation

enum CurrencyOptions {
    static let topCurrencies: [(code: String, label: String)] = [
        ("USD", "$ USD – US Dollar"),
        ("EUR", "€ EUR – Euro"),
        ("GBP", "£ GBP – British Pound"),
        ("JPY", "¥ JPY – Japanese Yen"),
        ("CNY", "¥ CNY – Chinese Yuan"),
    ]

    static let otherCurrencies: [(code: String, label: String)] = [
        ("AED", "د.إ AED – UAE Dirham"),
        ("ARS", "$ ARS – Argentine Peso"),
        ("AUD", "A$ AUD – Australian Dollar"),
        ("BDT", "৳ BDT – Bangladeshi Taka"),
        ("BGN", "лв BGN – Bulgarian Lev"),
        ("BHD", "BD BHD – Bahraini Dinar"),
        ("BRL", "R$ BRL – Brazilian Real"),
        ("CAD", "CA$ CAD – Canadian Dollar"),
        ("CHF", "CHF – Swiss Franc"),
        ("CLP", "$ CLP – Chilean Peso"),
        ("COP", "$ COP – Colombian Peso"),
        ("CZK", "Kč CZK – Czech Koruna"),
        ("DKK", "kr DKK – Danish Krone"),
        ("EGP", "E£ EGP – Egyptian Pound"),
        ("HKD", "HK$ HKD – Hong Kong Dollar"),
        ("HRK", "kn HRK – Croatian Kuna"),
        ("HUF", "Ft HUF – Hungarian Forint"),
        ("IDR", "Rp IDR – Indonesian Rupiah"),
        ("ILS", "₪ ILS – Israeli Shekel"),
        ("INR", "₹ INR – Indian Rupee"),
        ("ISK", "kr ISK – Icelandic Króna"),
        ("KRW", "₩ KRW – South Korean Won"),
        ("KWD", "KD KWD – Kuwaiti Dinar"),
        ("MXN", "MX$ MXN – Mexican Peso"),
        ("MYR", "RM MYR – Malaysian Ringgit"),
        ("NGN", "₦ NGN – Nigerian Naira"),
        ("NOK", "kr NOK – Norwegian Krone"),
        ("NZD", "NZ$ NZD – New Zealand Dollar"),
        ("PEN", "S/ PEN – Peruvian Sol"),
        ("PHP", "₱ PHP – Philippine Peso"),
        ("PKR", "₨ PKR – Pakistani Rupee"),
        ("PLN", "zł PLN – Polish Złoty"),
        ("QAR", "QR QAR – Qatari Riyal"),
        ("RON", "lei RON – Romanian Leu"),
        ("RUB", "₽ RUB – Russian Ruble"),
        ("SAR", "﷼ SAR – Saudi Riyal"),
        ("SEK", "kr SEK – Swedish Krona"),
        ("SGD", "S$ SGD – Singapore Dollar"),
        ("THB", "฿ THB – Thai Baht"),
        ("TRY", "₺ TRY – Turkish Lira"),
        ("TWD", "NT$ TWD – Taiwan Dollar"),
        ("UAH", "₴ UAH – Ukrainian Hryvnia"),
        ("VND", "₫ VND – Vietnamese Dong"),
        ("ZAR", "R ZAR – South African Rand"),
    ]
}
